### ISSUE TITLE
activitynet数据集下载问题

### ISSUE THREAD

**Issue by shadowclouds** [UCASUSTC/ActivityNet_Dataset_Download#1]
您好，我按照您的配置和官方的方法分别进行了activitynet数据集下载，均报错ERROR: Unable to download webpage: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(OSError(101, 'Network is unreachable'),))
上网寻找解决方案，好像是因为被墙了，无法下载数据集，请问您是否遇到过类似的问题？是否有解决的办法？

**Comment by onlyonewater** [comment]
我也遇到了这种情况，请问您是怎么解决的？

**Comment by shadowclouds** [comment]
最后翻墙了，没别的办法

**Comment by HN123-123** [comment]
下载的是视频都是文件格式
